# 可以尝试集成config-server来配置
spring:
  application:
    name: platform-gateway
  redis:
    host: localhost
    port: 6379
    database: 0
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      locator:
        enabled: false
        lower-case-service-id: true
      # routes:

server:
  port: 10004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

## 开启所有actuator-endpoint
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false




