server:
  port: 20006

spring:
  application:
    name: foodie-auth-service
  redis:
    database: 0
    host: localhost
    port: 6379
  zipkin:
    discoveryClientEnabled: true
    base-url: http://localhost:9411/
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
