############################################################
#配置数据源信息
############################################################
spring:
  datasource: #数据源的相关配置
    # url: jdbc:mariadb://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=TRUE
    url: ${mariadb.url}
    username: root
    password: ${mariadb.password}
  redis:
    # 单机实例
    database: 0
    host: localhost
    password:
    port: 6379
    # 哨兵模式
    #    sentinel:
    #      master: master
    #      nodes: localhost:26379
    # 集群模式
  #    cluster:
  #      nodes: localhost:6379,localhost:6379
############################################################
#web访问端口号 约定：8088
############################################################
server:
  port: 20001

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出mybatis日志记录

# 开启所有actuactor-endpoint
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  security:
#    enabled: false

hystrix:
  command:
    # 有的属性是默认值，写不写都行
    default:
      fallback:
        enabled: true
      circuitBreaker:
        enabled: true
        # 超过50%错误，那么开启熔断
        errorThresholdPercentage: 50
        # 5个request之后才进行统计
        requestVolumeThreshold: 5
        # 10秒之后进入半开状态
        sleepWindowInMilliseconds: 10000
        # forceClosed, forceOpen 强制关闭/开启熔断开关
      execution:
        timeout:
          enabled: true
        # 可以指定隔离方式是线程池还是信号量
        isolation:
          thread:
            interruptOnTimeout: true
            interruptOnFutureCancel: true
            timeoutInMilliseconds: 10000
      metrics:
        rollingStats:
          # 时间窗口统计
          timeInMilliseconds: 20000
          # numBuckets: 10
    #        rollingPercentile:
    #          # 时间窗口统计
    #          timeInMilliseconds: 20000
    #          # numBuckets: 10
    #          bucketSize: 300
    # 照这个方法，覆盖其他的属性
    loginFail:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
